<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<RootNamespace>Tsubaki</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseMaui>true</UseMaui>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.51" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tsubaki\Tsubaki.csproj" />
	</ItemGroup>

</Project>
